### ISSUE TITLE
Applying different functions on same input stream

### ISSUE THREAD

**Issue by steric85** [catdad/gulp-multistream#1]
Is it possible to apply different functions on same read stream and to write in two different write streams parallely?

**Comment by catdad** [comment]
In `gulp`, yes. Using this module, no. I don't think I have come across a use case like that. But it should be pretty trivial to write such a module. What is your use case?

**Comment by steric85** [comment]
I wish to apply two different compression libraries on the same input stream and direct them to two different output streams

**Comment by catdad** [comment]
I have not testing this just yet, but you should be able to use a stream combiner to accomplish this, without having to write a new gulp module or anything. Something like this:

```javascript
var gulp = require('gulp');
var combine = require('stream-combiner2');
var multistream = require('gulp-multistream');

gulp.task('compressAllTheThings', function () {
  var compress1 = combine(
    compressLib1(),
    gulp.dest('dest1')
  );
  var compress2 = combine(
    compressLib2(),
    gulp.dest('dest2')
  );

  return gulp.src('*.js')
    .pipe(multistream(
      compress1,
      compress2
    ));
});
